name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t scott-avatar-ai:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag scott-avatar-ai:latest docker.io/scottlaiq/scott-avatar-ai:latest
        docker push docker.io/scottlaiq/scott-avatar-ai:latest

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Pages
      uses: actions/configure-pages@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: web-build
        path: .

#     - name: Build with Jekyll
#       uses: actions/jekyll-build-pages@v1
#       with:
#         source: ./
#         destination: ./_site

#     - name: Upload artifact 
#       uses: actions/upload-artifact@v2
#       with:
#         name: web-build
#         path: _site/

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
