name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-image:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      run: |
        docker tag my-image:latest docker.io/${{ secrets.DOCKER_USERNAME }}/my-image:latest
        docker push docker.io/${{ secrets.DOCKER_USERNAME }}/my-image:latest

    - uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: .

  deploy: 

    needs: build
    permissions:
      id-token: write
      pages: write

    runs-on: ubuntu-latest

    steps:

    - uses: actions/download-artifact@v2
      with: 
        name: docker-image
        path: .

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        external_repository: ${{ secrets.DOCKER_USERNAME }}/my-image
        publish_branch: main
        publish_dir: .
        force_orphan: true
