name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t scott-avatar-ai:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag scott-avatar-ai:latest docker.io/scottlaiq/scott-avatar-ai:latest
        docker push docker.io/scottlaiq/scott-avatar-ai:latest
        
    - uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: .
        
  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

    - uses: actions/download-artifact@v2
      with:
        name: docker-image
        path: .

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        token: ${{ secrets.SECRET_NAME }}
